### ISSUE TITLE
Expedition Vikings

### ISSUE THREAD

**Issue by CamilleHbp** [WinSys323/FearlessDegeneration#13]
Could you decrypt the latest table from Expeditions Vikings, please?

https://fearlessrevolution.com/viewtopic.php?t=2148

Thank you so much!

**Comment by WinSys323** [comment]
[dump.zip](https://github.com/WinSys323/FearlessDegeneration/files/8014632/dump.zip)

**Comment by CamilleHbp** [comment]
Thank you!
